# Site settings
title: Tony Dias Web/Mobile/dApp Developer
description: Software development and digital solutions for persons and companies
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tony Dias
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: antoniocarlosdff@gmail.com
twitter_url: https://twitter.com/antoniocdff
github_url:  https://github.com/antoniocdff
linkedin_url:  https://www.linkedin.com/in/antoniocsis/

# Google-analytics
google-analytics:
  id: "UA-61729827-3"

exclude: ['package.json', 'src' , 'node_modules']
